---

- name: 'Include OS-specific variables'
  include_vars: "{{ ansible_os_family }}.yml"

- name: 'Ensure NFS is installed'
  package:
    name:  "{{ nfs_package }}"
    state: 'present'

- name: 'Ensure mount directories exist'
  file:
    path:  "{{ item.path }}"
    state: 'directory'
    mode:  "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop: "{{ aws_efs_paths|default([]) }}"

- name: 'Get current Availibity Zone from AWS'
  uri:
    url:            'http://169.254.169.254/latest/meta-data/placement/availability-zone'
    return_content: yes
  changed_when: False
  register: 'availability_zone'

- name: 'Ensure EFS volume is mounted'
  mount:
    name:   "{{ item.path }}"
    src:    "{{ availability_zone.content }}.{{ item.filesystem_id }}.efs.{{ item.region }}.amazonaws.com:/"
    fstype: 'nfs4'
    opts:   'nfsvers=4.1'
    state:  'mounted'
  loop: "{{ aws_efs_paths|default([]) }}"
